const fullCurrencyNames = {
    EUR: 'Euros',
    USD: 'USA dollars',
    CAD: 'Canadian dollars',

    HKD: 'Hong Kong dollars',
    ISK: 'Icelandic crowns',
    PHP: 'Philippine pesos',
    DKK: 'Danish Krones',
    HUF: 'Forints',
    CZK: 'Czech Korunas',
    AUD: 'Australian dollars',
    RON: 'New Romanian Leus',
    SEK: 'Swedish Krona',
    IDR: 'Indonesian Rupiahs',
    INR: 'Indian Rupees',
    BRL: 'Brazilian Reals',
    RUB: 'Russian Rubles',
    HRK: 'Croatian Kunas',
    JPY: 'Japanese Yens',
    THB: 'Bahts',
    CHF: 'Swiss Francs',
    SGD: 'Singapore Dollars',
    PLN: 'Zlotys',
    BGN: 'Bulgarian Levs',
    TRY: 'Turkish Liras',
    CNY: 'Chinese Yuan Renminbis',
    NOK: 'Norwegian Krones',
    NZD: 'New Zealand Dollars',
    ZAR: 'South African Rands',
    MXN: 'Mexican pesos',
    ILS: 'New Israeli Sheqels',
    GBP: 'Pounds Sterling',
    KRW: 'Korean Won',
    MYR: 'Malaysian Ringgits'
};

export default fullCurrencyNames;
